image:
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
  - Ubuntu2004
  - Ubuntu1804
  - Ubuntu1604

build_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release

test_script:
  - ctest -V -C Release
